Two fixes for pipeline-builder
1. Minor fix in update-pipeline.sh. It tries to add the build script even if that might not exist. This causes the job to fail for composite buildpacks.

2. Update create and package buildpack scripts such that they work and run out of the generated buildpack directory. This helps with a pack limitation that does not let you publish images when the `package.toml` file lives outside of the buildpack directory.

2.) fixes the following error:

```
pack -v buildpack package docker.io/dmikusa/rust -c ../package.toml --publish
Warning: A new '--target' flag is available to set the platform for the buildpack package, using 'linux' as default
Downloading buildpack from URI: file:///Users/dmikusa/Code/OSS/paketo-community/rust
Downloading buildpack dependency for platform linux
Downloading buildpack from image: docker.io/paketocommunity/rustup:1.11.0
ERROR: packaging dependencies (uri=docker://docker.io/paketocommunity/rustup:1.11.0,image=): extracting from registry docker://docker.io/paketocommunity/rustup:1.11.0: extracting buildpacks from docker.io/paketocommunity/rustup:1.11.0: could not find label io.buildpacks.buildpackage.metadata
```

Signed-off-by: Daniel Mikusa <dan@mikusa.com>